name: mybase
dependencies:
  - conda=22.11.1
  - python=3.10
  - conda-env
  - conda-build
  - conda-verify
  - _ipyw_jlab_nb_ext_conf
  - anaconda==2022.10=py310_0
  - anaconda-navigator
  - navigator-updater

