name: mybase
dependencies:
  - conda
  - python=3.11
  - conda-env
  - conda-build
  - conda-verify
  - _ipyw_jlab_nb_ext_conf
  - anaconda==2023.07=py311_1
  - anaconda-navigator
  - navigator-updater
