#!/usr/bin/env zsh

if [[ -f "${HOME}/.asdf/asdf.sh" ]]; then
  autoload -U +X compinit && compinit
  source "${HOME}/.asdf/asdf.sh"
  if [[ -f "${ASDF_DIR}/completions/asdf.bash" ]]; then
    source "${ASDF_DIR}/completions/asdf.bash"
  fi
fi

