#!/usr/bin/env zsh

if [[ $commands[minikube] ]]
then
  source <(minikube completion zsh)
  export MINIKUBE_WANTUPDATENOTIFICATION=true
  export MINIKUBE_WANTREPORTERROR=false
  export MINIKUBE_WANTREPORTERRORPROMPT=false
fi

if [[ $commands[kubectl] ]]
then
  source <(kubectl completion zsh)
fi

