#!/usr/bin/env zsh

export NVM_DIR="${HOME}/.nvm"
if [[ -s "${NVM_DIR}/nvm.sh" ]]
then
  source "${NVM_DIR}/nvm.sh"
fi
if [[ -s "${NVM_DIR}/bash_completion" ]]
then
  autoload -U +X compinit && compinit
  autoload -U +X bashcompinit && bashcompinit
  source "${NVM_DIR}/bash_completion"
fi

